CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS billing;
CREATE SCHEMA IF NOT EXISTS products;
CREATE SCHEMA IF NOT EXISTS stelargem;
CREATE SCHEMA IF NOT EXISTS stelarvacay;
CREATE SCHEMA IF NOT EXISTS stelarpeople;
CREATE SCHEMA IF NOT EXISTS agents;
CREATE SCHEMA IF NOT EXISTS governance;
CREATE SCHEMA IF NOT EXISTS worldgraph;
CREATE SCHEMA IF NOT EXISTS telemetry;

-- IDENTITY
CREATE TABLE IF NOT EXISTS identity.users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), email VARCHAR(255) UNIQUE NOT NULL, password_hash TEXT NOT NULL, mfa_secret TEXT, mfa_enabled BOOLEAN NOT NULL DEFAULT false, status VARCHAR(32) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS identity.sessions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE, token_hash TEXT NOT NULL UNIQUE, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS identity.roles (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES identity.users(id) ON DELETE CASCADE, product VARCHAR(64) NOT NULL, role VARCHAR(64) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

-- BILLING
CREATE TABLE IF NOT EXISTS billing.plans (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(128) NOT NULL UNIQUE, price_cents INTEGER NOT NULL DEFAULT 0, interval VARCHAR(32) NOT NULL DEFAULT 'month', features JSONB NOT NULL DEFAULT '[]', active BOOLEAN NOT NULL DEFAULT true, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS billing.subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES identity.users(id), plan_id UUID NOT NULL REFERENCES billing.plans(id), status VARCHAR(32) NOT NULL DEFAULT 'active', current_period_start TIMESTAMPTZ NOT NULL, current_period_end TIMESTAMPTZ NOT NULL, cancelled_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS billing.invoices (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), subscription_id UUID NOT NULL REFERENCES billing.subscriptions(id), amount_cents INTEGER NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'pending', issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), paid_at TIMESTAMPTZ);

-- PRODUCTS
CREATE TABLE IF NOT EXISTS products.product_registry (id VARCHAR(64) PRIMARY KEY, name VARCHAR(128) NOT NULL, slug VARCHAR(64) NOT NULL UNIQUE, description TEXT, status VARCHAR(32) NOT NULL DEFAULT 'active', config JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
INSERT INTO products.product_registry (id, name, slug, description) VALUES ('stelargem','StelarGem','stelargem','Spatial intelligence, neighborhood graph'),('stelarvacay','StelarVacay','stelarvacay','Budget-first travel planning'),('stelarpeople','StelarPeople','stelarpeople','Property and operator management') ON CONFLICT (id) DO NOTHING;

-- STELARGEM
CREATE TABLE IF NOT EXISTS stelargem.neighborhoods (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, city VARCHAR(128) NOT NULL, state VARCHAR(64), country VARCHAR(64) NOT NULL DEFAULT 'US', boundary JSONB, profile JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelargem.corridors (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, from_neighborhood_id UUID REFERENCES stelargem.neighborhoods(id), to_neighborhood_id UUID REFERENCES stelargem.neighborhoods(id), score DECIMAL(4,2), metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelargem.worldgraph_nodes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), node_type VARCHAR(64) NOT NULL, label VARCHAR(255) NOT NULL, properties JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelargem.worldgraph_edges (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), from_node_id UUID NOT NULL REFERENCES stelargem.worldgraph_nodes(id), to_node_id UUID NOT NULL REFERENCES stelargem.worldgraph_nodes(id), relation VARCHAR(128) NOT NULL, weight DECIMAL(6,4) DEFAULT 1.0, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

-- STELARVACAY
CREATE TABLE IF NOT EXISTS stelarvacay.destinations (id TEXT PRIMARY KEY, name VARCHAR(255) NOT NULL, region VARCHAR(255), country VARCHAR(255) DEFAULT 'India', base_cost_index DECIMAL(3,2) DEFAULT 1.0, description TEXT, avg_hotel_price DECIMAL(10,2), image_url TEXT, travel_profile VARCHAR(50), zone VARCHAR(50), nearest_rail_hub VARCHAR(255), nearest_airport VARCHAR(255), best_months TEXT[], avoid_months TEXT[], budget_highlights TEXT[], local_transport_note TEXT, sample_budget_per_day DECIMAL(10,2), sample_mid_budget_per_day DECIMAL(10,2), tags TEXT[], planning_score DECIMAL(3,2) DEFAULT 4.4);
CREATE TABLE IF NOT EXISTS stelarvacay.trips (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES identity.users(id), origin VARCHAR(255) NOT NULL, destination_id TEXT REFERENCES stelarvacay.destinations(id), start_date DATE NOT NULL, end_date DATE NOT NULL, traveler_count INTEGER DEFAULT 1, budget_level VARCHAR(50) DEFAULT 'smart', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarvacay.trip_budgets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), trip_id UUID NOT NULL REFERENCES stelarvacay.trips(id), transport_cost DECIMAL(10,2) DEFAULT 0, hotel_cost DECIMAL(10,2) DEFAULT 0, food_estimate DECIMAL(10,2) DEFAULT 0, activities_cost DECIMAL(10,2) DEFAULT 0, contingency DECIMAL(10,2) DEFAULT 0, total_cost DECIMAL(10,2) DEFAULT 0, breakdown JSONB NOT NULL DEFAULT '[]', transparency JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarvacay.trip_ratings (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), trip_id UUID NOT NULL REFERENCES stelarvacay.trips(id), cost_score INTEGER, comfort_score INTEGER, time_score INTEGER, reliability_score INTEGER, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarvacay.deals (id TEXT PRIMARY KEY, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, code VARCHAR(100) NOT NULL, discount_type VARCHAR(50), value DECIMAL(10,2), eligibility_rule TEXT, expires_at TEXT);

-- STELARPEOPLE
CREATE TABLE IF NOT EXISTS stelarpeople.assets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id VARCHAR(64) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL, address TEXT, city VARCHAR(128), state VARCHAR(64), zip VARCHAR(16), unit_count INTEGER DEFAULT 0, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarpeople.units (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID NOT NULL REFERENCES stelarpeople.assets(id), unit_number VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'vacant', market_rent_cents INTEGER, make_ready_progress INTEGER DEFAULT 0, metadata JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarpeople.leases (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), unit_id UUID NOT NULL REFERENCES stelarpeople.units(id), tenant_name VARCHAR(255) NOT NULL, monthly_rent_cents INTEGER NOT NULL, deposit_cents INTEGER, lease_start_date DATE NOT NULL, lease_end_date DATE, lease_ended_date DATE, status VARCHAR(32) NOT NULL DEFAULT 'active', custom_clauses JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarpeople.work_orders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID NOT NULL REFERENCES stelarpeople.assets(id), unit_id UUID REFERENCES stelarpeople.units(id), title VARCHAR(255) NOT NULL, category VARCHAR(128) NOT NULL, priority VARCHAR(32) NOT NULL DEFAULT 'medium', status VARCHAR(32) NOT NULL DEFAULT 'open', assigned_to VARCHAR(255), vendor_name VARCHAR(255), due_date DATE, estimated_cost_cents INTEGER, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarpeople.maintenance_snapshots (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID NOT NULL REFERENCES stelarpeople.assets(id), open_tickets INTEGER NOT NULL DEFAULT 0, unresolved_damages INTEGER NOT NULL DEFAULT 0, recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarpeople.prospects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), asset_id UUID REFERENCES stelarpeople.assets(id), name VARCHAR(255) NOT NULL, email VARCHAR(255), phone VARCHAR(32), stage VARCHAR(64) NOT NULL DEFAULT 'new', notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarpeople.prospect_activities (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), prospect_id UUID NOT NULL REFERENCES stelarpeople.prospects(id), activity_type VARCHAR(64) NOT NULL, notes TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stelarpeople.screening_applications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), prospect_id UUID REFERENCES stelarpeople.prospects(id), unit_id UUID REFERENCES stelarpeople.units(id), status VARCHAR(32) NOT NULL DEFAULT 'pending', decision VARCHAR(32), decision_notes TEXT, submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), decided_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS stelarpeople.market_snapshots (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), submarket_id VARCHAR(128) NOT NULL, submarket_label VARCHAR(255), market_avg_rent DECIMAL(10,2), occupancy_avg_pct DECIMAL(5,2), market_heat_score DECIMAL(4,2), source VARCHAR(255) NOT NULL, source_url TEXT, source_date DATE, confidence DECIMAL(3,2), recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

-- AGENTS
CREATE TABLE IF NOT EXISTS agents.agent_registry (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(128) NOT NULL UNIQUE, product VARCHAR(64) NOT NULL, role TEXT NOT NULL, capabilities JSONB NOT NULL DEFAULT '[]', status VARCHAR(32) NOT NULL DEFAULT 'active', config JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS agents.missions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(255) NOT NULL, product VARCHAR(64) NOT NULL, agent_ids JSONB NOT NULL DEFAULT '[]', status VARCHAR(32) NOT NULL DEFAULT 'pending', input JSONB NOT NULL DEFAULT '{}', output JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS agents.tasks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), mission_id UUID REFERENCES agents.missions(id), agent_id UUID REFERENCES agents.agent_registry(id), task_type VARCHAR(128) NOT NULL, status VARCHAR(32) NOT NULL DEFAULT 'pending', input JSONB NOT NULL DEFAULT '{}', output JSONB, error TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ);

-- GOVERNANCE
CREATE TABLE IF NOT EXISTS governance.tenants (id VARCHAR(64) PRIMARY KEY, name VARCHAR(255) NOT NULL UNIQUE, status VARCHAR(32) NOT NULL DEFAULT 'active', data_residency VARCHAR(64), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS governance.api_keys (id VARCHAR(64) PRIMARY KEY, tenant_id VARCHAR(64) NOT NULL REFERENCES governance.tenants(id), prefix VARCHAR(64) NOT NULL UNIQUE, secret_hash VARCHAR(128) NOT NULL, scopes JSONB NOT NULL DEFAULT '[]', allowed_models JSONB NOT NULL DEFAULT '[]', status VARCHAR(32) NOT NULL DEFAULT 'active', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS governance.routing_policies (id VARCHAR(64) PRIMARY KEY, tenant_id VARCHAR(64) NOT NULL REFERENCES governance.tenants(id), policy_name VARCHAR(255) NOT NULL, policy_json JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS governance.request_audit (id BIGSERIAL PRIMARY KEY, request_id VARCHAR(128) NOT NULL UNIQUE, tenant_id VARCHAR(64) NOT NULL, api_key_id VARCHAR(64) NOT NULL, provider_name VARCHAR(64) NOT NULL, model_name VARCHAR(128) NOT NULL, cache_hit BOOLEAN NOT NULL DEFAULT false, metadata_json JSONB NOT NULL DEFAULT '{}', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS governance.quota_snapshots (id BIGSERIAL PRIMARY KEY, tenant_id VARCHAR(64) NOT NULL, period VARCHAR(32) NOT NULL, requests_used INTEGER NOT NULL DEFAULT 0, tokens_used INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS governance.claim_reviews (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), content_hash VARCHAR(64) NOT NULL, product VARCHAR(64) NOT NULL, agent_name VARCHAR(128), classification VARCHAR(64) NOT NULL, risk_score DECIMAL(3,2) NOT NULL, decision VARCHAR(32) NOT NULL, reviewer_notes TEXT, reviewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW());

-- WORLDGRAPH
CREATE TABLE IF NOT EXISTS worldgraph.entities (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), entity_type VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, canonical_id VARCHAR(255) UNIQUE, properties JSONB NOT NULL DEFAULT '{}', source VARCHAR(128), confidence DECIMAL(3,2) DEFAULT 1.0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS worldgraph.relations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), from_entity_id UUID NOT NULL REFERENCES worldgraph.entities(id), to_entity_id UUID NOT NULL REFERENCES worldgraph.entities(id), relation_type VARCHAR(128) NOT NULL, weight DECIMAL(6,4) DEFAULT 1.0, properties JSONB NOT NULL DEFAULT '{}', source VARCHAR(128), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_worldgraph_relations_from ON worldgraph.relations(from_entity_id);
CREATE INDEX IF NOT EXISTS idx_worldgraph_relations_to ON worldgraph.relations(to_entity_id);
CREATE INDEX IF NOT EXISTS idx_worldgraph_entities_type ON worldgraph.entities(entity_type);

-- TELEMETRY
CREATE TABLE IF NOT EXISTS telemetry.events (id BIGSERIAL PRIMARY KEY, event_type VARCHAR(128) NOT NULL, product VARCHAR(64) NOT NULL, tenant_id VARCHAR(64), user_id UUID, agent_name VARCHAR(128), request_id VARCHAR(128), trace_id VARCHAR(128), properties JSONB NOT NULL DEFAULT '{}', occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS telemetry.errors (id BIGSERIAL PRIMARY KEY, error_type VARCHAR(128) NOT NULL, product VARCHAR(64) NOT NULL, service VARCHAR(128) NOT NULL, message TEXT NOT NULL, stack_trace TEXT, request_id VARCHAR(128), trace_id VARCHAR(128), severity VARCHAR(32) NOT NULL DEFAULT 'error', occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS telemetry.health_checks (id BIGSERIAL PRIMARY KEY, service VARCHAR(128) NOT NULL, status VARCHAR(32) NOT NULL, response_ms INTEGER, checked_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_telemetry_events_product ON telemetry.events(product, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_errors_product ON telemetry.errors(product, occurred_at DESC);
