import { useState } from 'react';
import { api } from '../../lib/api.ts';

type TransformType = 'staged' | 'renovated' | 'seasonal_spring' | 'seasonal_winter' | 'potential_max' | 'curb_appeal';

interface TransformResult {
  tour_id: string;
  transform_type: string;
  transform_label: string;
  model: string;
  output_image_b64: string | null;
  label: string;
  available: boolean;
}

interface Props {
  tourId: string;
  sourceImageB64: string | null;
}

const TRANSFORMS: Array<{ key: TransformType; label: string; desc: string; icon: string }> = [
  { key: 'staged', label: 'Staged', desc: 'Add furniture & styling', icon: '🛋' },
  { key: 'renovated', label: 'Renovated', desc: 'Modern finishes & fixtures', icon: '🔨' },
  { key: 'seasonal_spring', label: 'Spring', desc: 'Blooming landscaping', icon: '🌸' },
  { key: 'seasonal_winter', label: 'Winter', desc: 'Snow & warm lighting', icon: '❄' },
  { key: 'potential_max', label: 'Max Potential', desc: 'Full renovation vision', icon: '✨' },
  { key: 'curb_appeal', label: 'Curb Appeal', desc: 'Enhanced exterior', icon: '🏡' },
];

const CREATIVE_LABEL =
  'AI Creative Preview — Not a verified source. Generated by Imagen 3 / Genie 3. Does not represent actual property condition.';

export default function GeniePreviewPanel({ tourId, sourceImageB64 }: Props) {
  const [selected, setSelected] = useState<TransformType | null>(null);
  const [results, setResults] = useState<Map<TransformType, TransformResult>>(new Map());
  const [loading, setLoading] = useState<TransformType | null>(null);
  const [error, setError] = useState('');

  if (!sourceImageB64) {
    return (
      <div className="rounded-xl border border-dashed border-slate-200 p-6 text-center">
        <p className="text-sm text-slate-400">Upload a property photo above to enable creative previews.</p>
      </div>
    );
  }

  async function requestTransform(type: TransformType) {
    if (results.has(type)) {
      setSelected(type);
      return;
    }

    setLoading(type);
    setError('');
    setSelected(type);

    try {
      const res = await api.post<TransformResult>('/api/tour/genie-transform', {
        tour_id: tourId,
        source_image_b64: sourceImageB64,
        transform_type: type,
      });
      setResults((prev) => new Map(prev).set(type, res));
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Transform failed.');
    } finally {
      setLoading(null);
    }
  }

  const currentResult = selected ? results.get(selected) : null;

  return (
    <div className="space-y-4">
      {/* Mandatory creative preview header */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl px-4 py-3">
        <div className="flex items-start gap-2">
          <span className="text-amber-500 text-lg shrink-0">⚡</span>
          <div>
            <p className="text-xs font-semibold text-amber-800">AI Creative Previews</p>
            <p className="text-xs text-amber-700 mt-0.5">{CREATIVE_LABEL}</p>
          </div>
        </div>
      </div>

      {/* Transform selector */}
      <div className="grid grid-cols-3 gap-2">
        {TRANSFORMS.map((t) => (
          <button
            key={t.key}
            onClick={() => requestTransform(t.key)}
            disabled={loading !== null}
            className={`rounded-lg border p-2.5 text-left transition-all ${
              selected === t.key
                ? 'border-emerald-500 bg-emerald-50'
                : 'border-slate-200 hover:border-slate-300 hover:bg-slate-50'
            } disabled:opacity-50`}
          >
            <div className="text-lg mb-0.5">{t.icon}</div>
            <p className="text-xs font-semibold text-slate-700">{t.label}</p>
            <p className="text-xs text-slate-400 leading-tight">{t.desc}</p>
            {results.has(t.key) && (
              <span className="text-xs text-emerald-600 font-medium">✓ Generated</span>
            )}
          </button>
        ))}
      </div>

      {/* Output */}
      {loading && (
        <div className="rounded-xl bg-slate-100 h-48 flex items-center justify-center">
          <div className="text-center">
            <div className="w-8 h-8 border-2 border-emerald-400 border-t-transparent rounded-full animate-spin mx-auto mb-2" />
            <p className="text-xs text-slate-500">Generating creative preview…</p>
          </div>
        </div>
      )}

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 text-xs rounded-lg px-4 py-3">
          {error}
        </div>
      )}

      {currentResult && !loading && (
        <div className="rounded-xl overflow-hidden border border-amber-200">
          {currentResult.output_image_b64 ? (
            <img
              src={`data:image/jpeg;base64,${currentResult.output_image_b64}`}
              alt={`${currentResult.transform_label} creative preview`}
              className="w-full object-cover"
            />
          ) : (
            <div className="bg-slate-100 h-48 flex items-center justify-center">
              <p className="text-sm text-slate-400">Preview generation returned no image.</p>
            </div>
          )}

          {/* Always-visible label on the image output */}
          <div className="bg-amber-50 border-t border-amber-200 px-4 py-2">
            <div className="flex items-center gap-2">
              <span className="text-amber-500">⚡</span>
              <div>
                <p className="text-xs font-semibold text-amber-800">
                  {currentResult.transform_label} — AI Creative Preview
                </p>
                <p className="text-xs text-amber-600">
                  {CREATIVE_LABEL}
                </p>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Original side by side (if result available) */}
      {currentResult?.output_image_b64 && (
        <div className="grid grid-cols-2 gap-2">
          <div className="rounded-lg overflow-hidden">
            <img
              src={`data:image/jpeg;base64,${sourceImageB64}`}
              alt="Original"
              className="w-full aspect-video object-cover"
            />
            <p className="text-center text-xs text-slate-500 py-1 bg-slate-50">Original</p>
          </div>
          <div className="rounded-lg overflow-hidden border border-amber-200">
            <img
              src={`data:image/jpeg;base64,${currentResult.output_image_b64}`}
              alt="Preview"
              className="w-full aspect-video object-cover"
            />
            <p className="text-center text-xs text-amber-600 py-1 bg-amber-50">⚡ AI Preview</p>
          </div>
        </div>
      )}
    </div>
  );
}
