"""
Gemini Vision service — image analysis and creative preview generation.
Uses google-genai SDK (google.genai), which supports both text and vision in one client.
"""

import base64
import json
import logging
from typing import Any

logger = logging.getLogger(__name__)

# ─── Prompts ─────────────────────────────────────────────────────────────────

IMAGE_ANALYSIS_SYSTEM = (
    "You are a real estate property intelligence analyst. "
    "Analyze the provided property images and return a structured JSON assessment. "
    "Identify: building style and era, visible condition signals, potential listing fraud indicators, "
    "neighborhood context clues, and estimate property attributes where visible. "
    "Be factual and specific. Flag any stock photo signals, CGI artifacts, or EXIF/metadata anomalies. "
    "Return ONLY valid JSON, no markdown, no code fences."
)

IMAGE_ANALYSIS_SCHEMA = """
{
  "tour_id": "<provided>",
  "model": "gemini-2.0-flash",
  "images": [
    {
      "index": 0,
      "detected_type": "exterior_front|exterior_side|interior_living|interior_kitchen|interior_bedroom|interior_bathroom|neighborhood|aerial|unknown",
      "building_style": "string|null",
      "era": "string|null",
      "condition_signals": ["string"],
      "red_flags": ["string"],
      "stock_photo_risk": 0.0,
      "cgi_artifact_risk": 0.0,
      "estimated_sqft_from_room": number|null,
      "neighborhood_context": "string|null",
      "notable_features": ["string"],
      "mismatch_with_listing": ["string"]
    }
  ],
  "fraud_assessment": {
    "overall_risk_score": 0.0,
    "risk_level": "very_low|low|medium|high|critical",
    "flags": [
      {
        "type": "stock_photo|cgi_render|season_mismatch|address_mismatch|size_inconsistency|amenity_misrepresentation|duplicate_image|synthetic_indicator",
        "description": "string",
        "severity": "low|medium|high|critical",
        "recommendation": "string"
      }
    ],
    "mismatch_signals": ["string"],
    "verification_recommended": boolean
  },
  "enhancement_narrative": "string — 2-3 sentences grounding the AI tour in what was actually seen in photos",
  "disclaimer": "Analysis by Gemini AI. Independent verification recommended."
}
"""

TRANSFORM_PROMPTS: dict[str, dict[str, str]] = {
    "staged": {
        "prompt": (
            "Transform this property photo into a professionally staged real estate image. "
            "Add tasteful furniture, art, plants, and warm lighting. Keep the same room geometry and dimensions. "
            "Style: contemporary neutral staging, warm tones, high-end real estate photography quality."
        ),
        "label": "Virtually Staged",
    },
    "renovated": {
        "prompt": (
            "Transform this property photo to show a modern renovation. "
            "Update finishes: new countertops (quartz or marble), fresh neutral paint, modern fixtures and hardware. "
            "Preserve the room layout. Style: clean contemporary renovation, real estate photography."
        ),
        "label": "Renovation Preview",
    },
    "seasonal_spring": {
        "prompt": (
            "Transform this exterior property photo to show it in peak spring. "
            "Add blooming trees, green lawn, flowers, fresh mulch. Golden hour lighting. "
            "Keep the building structure identical."
        ),
        "label": "Spring Preview",
    },
    "seasonal_winter": {
        "prompt": (
            "Transform this exterior property photo to show it in winter. "
            "Add light snow on lawn and roof edges, bare trees, warm glowing windows. "
            "Keep the building structure identical. Cozy, welcoming feeling."
        ),
        "label": "Winter Preview",
    },
    "potential_max": {
        "prompt": (
            "Transform this property photo to show its full renovation potential. "
            "Complete gut renovation: best possible version of this space. "
            "New everything — flooring, walls, fixtures, lighting. High-end finishes. "
            "Keep original layout and square footage."
        ),
        "label": "Maximum Potential Preview",
    },
    "curb_appeal": {
        "prompt": (
            "Transform this exterior property photo to maximize curb appeal. "
            "Fresh exterior paint, power-washed driveway, manicured lawn, trimmed hedges, new mulch, "
            "updated front door, window boxes with flowers. Same structure."
        ),
        "label": "Curb Appeal Preview",
    },
}

CREATIVE_LABEL = "AI Creative Preview — Not a verified source. Generated by Imagen 3 / Genie 3. Does not represent actual property condition."


# ─── Image Analysis ──────────────────────────────────────────────────────────

async def analyze_images(
    tour_id: str,
    image_data: list[tuple[str, bytes]],
    listing_facts: dict[str, Any],
    api_key: str,
) -> dict:
    try:
        from google import genai
        from google.genai import types as genai_types
    except ImportError as exc:
        raise RuntimeError(
            "google-genai package not installed. Run: uv pip install google-genai"
        ) from exc

    client = genai.Client(api_key=api_key)

    facts_text = "; ".join(f"{k}: {v}" for k, v in list(listing_facts.items())[:15])
    listing_block = f"Listing claims: {facts_text}." if facts_text else "No listing facts provided."

    parts: list[Any] = [
        genai_types.Part.from_text(
            f"Tour ID: {tour_id}\n{listing_block}\n\nAnalyze all provided images.\n\nSchema:\n{IMAGE_ANALYSIS_SCHEMA}"
        )
    ]

    for mime, content in image_data:
        parts.append(genai_types.Part.from_bytes(data=content, mime_type=mime))

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=[genai_types.Content(role="user", parts=parts)],
        config=genai_types.GenerateContentConfig(
            system_instruction=IMAGE_ANALYSIS_SYSTEM,
            temperature=0.1,
            max_output_tokens=4000,
        ),
    )

    raw = response.text.strip() if response.text else ""
    if raw.startswith("```"):
        raw = raw.split("\n", 1)[1] if "\n" in raw else raw
        raw = raw.rsplit("```", 1)[0].strip()

    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        logger.warning("gemini_vision_json_parse_failed preview=%s", raw[:300])
        return {
            "tour_id": tour_id,
            "model": "gemini-2.0-flash",
            "images": [],
            "fraud_assessment": {"overall_risk_score": 0, "risk_level": "unknown", "flags": [], "mismatch_signals": [], "verification_recommended": True},
            "enhancement_narrative": "Image analysis completed but structured output parsing failed. Review images manually.",
            "disclaimer": "Analysis by Gemini AI. Independent verification recommended.",
            "_raw": raw[:1000],
        }


# ─── Creative Transform (Imagen 3 / Genie 3 bridge) ─────────────────────────

async def generate_creative_transform(
    tour_id: str,
    image_bytes: bytes,
    transform_type: str,
    api_key: str,
) -> dict:
    """
    Generate a creative property transformation using Imagen 3.
    Genie 3's environment generation API will replace this when publicly available.
    """
    transform = TRANSFORM_PROMPTS.get(transform_type)
    if not transform:
        raise ValueError(f"Unknown transform type: {transform_type}")

    try:
        from google import genai
        from google.genai import types as genai_types
    except ImportError as exc:
        raise RuntimeError("google-genai package not installed.") from exc

    client = genai.Client(api_key=api_key)

    # Gemini 2.0 Flash with image generation capability
    # Falls back to description-based generation when image editing isn't available
    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash-preview-image-generation",
            contents=[
                genai_types.Content(
                    role="user",
                    parts=[
                        genai_types.Part.from_bytes(data=image_bytes, mime_type="image/jpeg"),
                        genai_types.Part.from_text(transform["prompt"]),
                    ],
                )
            ],
            config=genai_types.GenerateContentConfig(
                response_modalities=["IMAGE", "TEXT"],
                temperature=0.4,
            ),
        )

        output_image_b64 = None
        for part in response.candidates[0].content.parts:
            if part.inline_data and part.inline_data.mime_type.startswith("image/"):
                output_image_b64 = base64.b64encode(part.inline_data.data).decode()
                break

        return {
            "tour_id": tour_id,
            "transform_type": transform_type,
            "transform_label": transform["label"],
            "model": "gemini-2.0-flash-exp-image-generation",
            "output_image_b64": output_image_b64,
            "label": CREATIVE_LABEL,
            "available": output_image_b64 is not None,
        }

    except Exception:
        # Imagen 3 fallback via Vertex AI endpoint
        logger.info("gemini_image_gen_unavailable attempting imagen3_fallback transform=%s", transform_type)
        return await _imagen3_fallback(tour_id, image_bytes, transform, api_key)


async def _imagen3_fallback(
    tour_id: str,
    image_bytes: bytes,
    transform: dict[str, str],
    api_key: str,
) -> dict:
    """
    Imagen 3 via google-genai SDK.
    Returns generated image or a placeholder when API quota/access is unavailable.
    """
    try:
        from google import genai
        from google.genai import types as genai_types
    except ImportError as exc:
        raise RuntimeError("google-genai package not installed.") from exc

    client = genai.Client(api_key=api_key)

    response = client.models.generate_images(
        model="imagen-3.0-generate-002",
        prompt=transform["prompt"],
        config=genai_types.GenerateImagesConfig(
            number_of_images=1,
            aspect_ratio="4:3",
        ),
    )

    output_image_b64 = None
    if response.generated_images:
        img = response.generated_images[0].image
        if img and img.image_bytes:
            output_image_b64 = base64.b64encode(img.image_bytes).decode()

    return {
        "tour_id": tour_id,
        "transform_type": transform.get("label", "transform"),
        "transform_label": transform["label"],
        "model": "imagen-3.0-generate-002",
        "output_image_b64": output_image_b64,
        "label": CREATIVE_LABEL,
        "available": output_image_b64 is not None,
    }
